### These settings are for erelsgl.github.io

# Site settings
url: "http://erelsgl.github.io" # the base hostname & protocol for your site
baseurl: #empty
permalink: pretty    # no .html suffix

# Build settings
markdown: kramdown

collections:
  topics:
    output: true

defaults:
  -
    scope:
      path: _posts
    values:
      layout: post
  -
    scope:
      path: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: topics
    values:
      layout: topic
